name       : rustup
version    : 1.25.2
release    : 17
source     :
    - https://github.com/rust-lang/rustup/archive/1.25.2.tar.gz : dc9bb5d3dbac5cea9afa9b9c3c96fcf644a1e7ed6188a6b419dfe3605223b5f3
license    :
    - Apache-2.0
    - MIT
component  : programming.tools
summary    : The Rust toolchain installer.
description: |
    The Rust toolchain installer.
builddeps  :
    - cargo
    - curl
conflicts  :
    - rust
    - cargo
networking : yes
build      : |
    cargo build --release --features no-self-update
install    : |
    install -Dm00755 target/release/rustup-init $installdir/usr/bin/rustup

    binlinks=('cargo' 'rustc' 'rustdoc' 'rust-gdb' 'rust-gdbui' 'rust-lldb')

    for link in "${binlinks[@]}"; do
        ln -s /usr/bin/rustup $installdir/usr/bin/$link
    done

