name       : rustup
version    : 1.18.1
release    : 3
source     :
    - https://github.com/rust-lang/rustup.rs/archive/1.18.1.tar.gz : a53ad8a9da617dbdf3bcad31eddb9483ba9cfa73f4e5cfbbc86de4d3b28338a9
license    :
    - Apache-2.0
    - MIT
component  : programming.tools
summary    : The Rust toolchain installer.
description: |
    The Rust toolchain installer.
builddeps  :
    - cargo
    - curl
networking : yes
build      : |
    cargo build --release --features no-self-update
install    : |
    install -Dm00755 target/release/rustup-init $installdir/usr/bin/rustup
