name       : rustup
version    : 1.21.1
release    : 10
source     :
    - https://github.com/rust-lang/rustup/archive/1.21.1.tar.gz : 3dd54cb15313ff01c930ad4e36326f7d60caadd2d6707790d83bea26fbb8bbe1
license    :
    - Apache-2.0
    - MIT
component  : programming.tools
summary    : The Rust toolchain installer.
description: |
    The Rust toolchain installer.
builddeps  :
    - cargo
    - curl
conflicts  :
    - rust
    - cargo
networking : yes
build      : |
    cargo build --release --features no-self-update
install    : |
    install -Dm00755 target/release/rustup-init $installdir/usr/bin/rustup

    binlinks=('cargo' 'rustc' 'rustdoc' 'rust-gdb' 'rust-gdbui' 'rust-lldb')

    for link in "${binlinks[@]}"; do
        ln -s /usr/bin/rustup $installdir/usr/bin/$link
    done

