name       : rustup
version    : 1.20.1
release    : 8
source     :
    - https://github.com/rust-lang/rustup.rs/archive/1.20.1.tar.gz : f93caf7a856a25f5d10bdcfa6bdebe5bbea686140f2a9d40278c933fe2efaa0c
license    :
    - Apache-2.0
    - MIT
component  : programming.tools
summary    : The Rust toolchain installer.
description: |
    The Rust toolchain installer.
builddeps  :
    - cargo
    - curl
conflicts  :
    - rust
    - cargo
networking : yes
build      : |
    cargo build --release --features no-self-update
install    : |
    install -Dm00755 target/release/rustup-init $installdir/usr/bin/rustup

    binlinks=('cargo' 'rustc' 'rustdoc' 'rust-gdb' 'rust-gdbui' 'rust-lldb')

    for link in "${binlinks[@]}"; do
        ln -s /usr/bin/rustup $installdir/usr/bin/$link
    done

