name       : rustup
version    : 1.26.0
release    : 18
source     :
    - https://github.com/rust-lang/rustup/archive/1.26.0.tar.gz : 6f20ff98f2f1dbde6886f8d133fe0d7aed24bc76c670ea1fca18eb33baadd808
license    :
    - Apache-2.0
    - MIT
component  : programming.tools
summary    : The Rust toolchain installer.
description: |
    The Rust toolchain installer.
builddeps  :
    - pkgconfig(liblzma)
    - cargo
    - curl
conflicts  :
    - rust
    - cargo
networking : yes
build      : |
    cargo build --release --features no-self-update
install    : |
    install -Dm00755 target/release/rustup-init $installdir/usr/bin/rustup

    binlinks=('cargo' 'rustc' 'rustdoc' 'rust-gdb' 'rust-gdbui' 'rust-lldb')

    for link in "${binlinks[@]}"; do
        ln -s /usr/bin/rustup $installdir/usr/bin/$link
    done

